# Numpy Random Array

 - 1. rand : Generates Random numbers between 0 and 1 (uniform distribution).
 - 2. randn : Grenerates Random numbers following a normal distribution (mean = 0, std = 1).
 - 3. ranf : Generates Random floats between 0 and 1 (similar to rand, but accepts a shape as an argument instead of dimensions).
 - 4. randint

In [1]:
import numpy as np

# 1. rand function
- Generates Random numbers between 0 and 1 (uniform distribution).

In [2]:
arr = np.random.rand(3)
print(arr)

[0.885965   0.74655113 0.0239433 ]


# 2. randn function
- Random numbers following a normal distribution (mean = 0, std = 1).

In [3]:
arr = np.random.randn(5,3)
print(arr)
print(arr.dtype)

[[-1.42252524  0.61780354  0.32929628]
 [-1.20583167  0.44823689  1.47071622]
 [ 0.6358297   0.47018777 -2.41340811]
 [ 0.09138235 -0.44075048 -1.14055716]
 [-0.05668153  1.08241253 -0.70157003]]
float64


# 3. ranf function
- Random floats between 0 and 1 (similar to rand, but accepts a shape as an argument instead of dimensions).

In [4]:
arr = np.random.ranf(3)
print(arr)
print(arr.dtype)

[0.86221944 0.23215039 0.13228936]
float64


# 4. randint function
- Random integers from low (inclusive) to high (exclusive).

        - Usage: numpy.random.randint(low, high, size)

In [5]:
arr = np.random.randint(10,20,3)
print(arr)
print(arr.ndim)

[16 15 11]
1


# Extras

In [6]:
arr = np.random.randint(5,20,3)*10
print(arr)

[140  50 120]
