# Broadcasting

    - Broadcasting Rules
- Same Dimension
- (1x3) = (3x1)

In [3]:
import numpy as np

    - Same Dimension

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,4,6])
print(arr1+arr2)

print(arr1.shape)

[3 6 9]
(3,)


    - (1x3) = (3x1)

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([[2], [4], [6]])
print(arr1+arr2)

print(arr1.shape)
print(arr2.shape)

[[3 4 5]
 [5 6 7]
 [7 8 9]]
(3,)
(3, 1)


    - Broadcasting error

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4,5])
result = arr1[:,np.newaxis]+ arr2
print(result)

[[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([[2,3], [4,3], [6,3]])
result = arr1[:,np.newaxis]+ arr2
print(result)

[[3 4]
 [6 5]
 [9 6]]
